# Generated by Django 5.1.3 on 2025-04-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_status_order_is_paid_and_more'),
        ('jewelries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelries.jewelry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.order')),
            ],
        ),
    ]
