# Generated by Django 5.1.3 on 2025-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Rings', 'Rings'), ('Necklaces', 'Necklaces'), ('Earrings', 'Earrings'), ('Bracelets', 'Bracelets'), ('Anklets', 'Anklets'), ('Brooches & Pins', 'Brooches & Pins'), ('Charms', 'Charms'), ('Jewelry Sets', 'Jewelry Sets'), ('Watches', 'Watches')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
